# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChatRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChatRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChatRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChatRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChatRequest
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatRequest
    def ModelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatRequest
    def Messages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from sao.ipc.ChatMessage import ChatMessage
            obj = ChatMessage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChatRequest
    def MessagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ChatRequest
    def MessagesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ChatRequest
    def Provider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatRequest
    def ApiBase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatRequest
    def ApiKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ChatRequestStart(builder):
    builder.StartObject(6)

def Start(builder):
    ChatRequestStart(builder)

def ChatRequestAddSessionId(builder, sessionId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder, sessionId):
    ChatRequestAddSessionId(builder, sessionId)

def ChatRequestAddModelId(builder, modelId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)

def AddModelId(builder, modelId):
    ChatRequestAddModelId(builder, modelId)

def ChatRequestAddMessages(builder, messages):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(messages), 0)

def AddMessages(builder, messages):
    ChatRequestAddMessages(builder, messages)

def ChatRequestStartMessagesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMessagesVector(builder, numElems):
    return ChatRequestStartMessagesVector(builder, numElems)

def ChatRequestCreateMessagesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateMessagesVector(builder, data):
    ChatRequestCreateMessagesVector(builder, data)

def ChatRequestAddProvider(builder, provider):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(provider), 0)

def AddProvider(builder, provider):
    ChatRequestAddProvider(builder, provider)

def ChatRequestAddApiBase(builder, apiBase):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(apiBase), 0)

def AddApiBase(builder, apiBase):
    ChatRequestAddApiBase(builder, apiBase)

def ChatRequestAddApiKey(builder, apiKey):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(apiKey), 0)

def AddApiKey(builder, apiKey):
    ChatRequestAddApiKey(builder, apiKey)

def ChatRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChatRequestEnd(builder)
