# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListModelsRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListModelsRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListModelsRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    def Provider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ListModelsRequestStart(builder):
    builder.StartObject(1)

def Start(builder):
    ListModelsRequestStart(builder)

def ListModelsRequestAddProvider(builder, provider):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(provider), 0)

def AddProvider(builder, provider):
    ListModelsRequestAddProvider(builder, provider)

def ListModelsRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListModelsRequestEnd(builder)