# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChatResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChatResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChatResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChatResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChatResponse
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatResponse
    def Chunk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatResponse
    def IsFinal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ChatResponse
    def ToolCallsJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ChatResponseStart(builder):
    builder.StartObject(4)

def Start(builder):
    ChatResponseStart(builder)

def ChatResponseAddSessionId(builder, sessionId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder, sessionId):
    ChatResponseAddSessionId(builder, sessionId)

def ChatResponseAddChunk(builder, chunk):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(chunk), 0)

def AddChunk(builder, chunk):
    ChatResponseAddChunk(builder, chunk)

def ChatResponseAddIsFinal(builder, isFinal):
    builder.PrependBoolSlot(2, isFinal, 0)

def AddIsFinal(builder, isFinal):
    ChatResponseAddIsFinal(builder, isFinal)

def ChatResponseAddToolCallsJson(builder, toolCallsJson):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(toolCallsJson), 0)

def AddToolCallsJson(builder, toolCallsJson):
    ChatResponseAddToolCallsJson(builder, toolCallsJson)

def ChatResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChatResponseEnd(builder)
