# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChatMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChatMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChatMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChatMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChatMessage
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ChatMessage
    def Content(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ChatMessageStart(builder):
    builder.StartObject(2)

def Start(builder):
    ChatMessageStart(builder)

def ChatMessageAddRole(builder, role):
    builder.PrependInt8Slot(0, role, 0)

def AddRole(builder, role):
    ChatMessageAddRole(builder, role)

def ChatMessageAddContent(builder, content):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)

def AddContent(builder, content):
    ChatMessageAddContent(builder, content)

def ChatMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChatMessageEnd(builder)
