# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ipc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ListModelsResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListModelsResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsListModelsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ListModelsResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListModelsResponse
    def Provider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ListModelsResponse
    def Models(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ListModelsResponse
    def ModelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ListModelsResponse
    def ModelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ListModelsResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ListModelsResponseStart(builder):
    builder.StartObject(3)

def Start(builder):
    ListModelsResponseStart(builder)

def ListModelsResponseAddProvider(builder, provider):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(provider), 0)

def AddProvider(builder, provider):
    ListModelsResponseAddProvider(builder, provider)

def ListModelsResponseAddModels(builder, models):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(models), 0)

def AddModels(builder, models):
    ListModelsResponseAddModels(builder, models)

def ListModelsResponseStartModelsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartModelsVector(builder, numElems):
    return ListModelsResponseStartModelsVector(builder, numElems)

def ListModelsResponseCreateModelsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateModelsVector(builder, data):
    ListModelsResponseCreateModelsVector(builder, data)

def ListModelsResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    ListModelsResponseAddError(builder, error)

def ListModelsResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ListModelsResponseEnd(builder)
