# Generated by the gRPC FlatBuffers compiler. DO NOT EDIT!

import flatbuffers
import grpc

from sao.ipc.ChatRequest import ChatRequest
from sao.ipc.ChatResponse import ChatResponse
from sao.ipc.ListModelsRequest import ListModelsRequest
from sao.ipc.ListModelsResponse import ListModelsResponse


class SaoServiceStub(object):
  '''Interface exported by the server.'''

  def __init__(self, channel):
    '''Constructor.

    Args:
      channel: A grpc.Channel.
    '''

    self.ChatStream = channel.unary_stream(
      method='/sao.ipc.SaoService/ChatStream')

    self.ListModels = channel.unary_unary(
      method='/sao.ipc.SaoService/ListModels')


class SaoServiceServicer(object):
  '''Interface exported by the server.'''

  def ChatStream(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListModels(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SaoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
    'ChatStream': grpc.unary_stream_rpc_method_handler(
      servicer.ChatStream),
    'ListModels': grpc.unary_unary_rpc_method_handler(
      servicer.ListModels),
  }

  generic_handler = grpc.method_handlers_generic_handler(
    'sao.ipc.SaoService', rpc_method_handlers)

  server.add_generic_rpc_handlers((generic_handler,))


